export interface IAuthenticatedClient {
  request: Function;
  futuresGetTicker: Function;
  futuresNewTrade: Function;
  futuresUpdateTrade: Function;
  futuresCloseTrade: Function;
  futuresCloseAllTrades: Function;
  futuresCancelTrade: Function;
  futuresCancelAllTrades: Function;
  futuresCashinTrade: Function;
  futuresAddMarginTrade: Function;
  futuresGetTrades: Function;
  futuresPriceHistory: Function;
  futuresIndexHistory: Function;
  futuresFixingHistory: Function;
  futuresCarryFeesHistory: Function;
  userGet: Function;
  userUpdate: Function;
  userDeposit: Function;
  userDepositHistory: Function;
  userWithdraw: Function;
  userWithdrawUsd: Function;
  userWithdrawHistory: Function;
  optionsInstrument: Function;
  optionsInstruments: Function;
  optionsMarket: Function;
  optionsNewTrade: Function;
  optionsGetTrades: Function;
  optionsCloseTrade: Function;
  optionsCloseAllTrades: Function;
  optionsUpdateSettlement: Function;
}
export interface IUserLnMarket{
  uid: string,
  role: string,
  balance: number,
  username: string,
  login: string,
  synthetic_usd_balance: number,
  linkingpublickey: string,
  show_leaderboard: boolean,
  email: string,
  email_confirmed: boolean,
  use_taproot_addresses: boolean,
  account_type: string,
  auto_withdraw_enabled: boolean,
  auto_withdraw_lightning_address: string,
  totp_enabled: boolean,
  webauthn_enabled: boolean,
  fee_tier: number,
  locale: string
}